apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sRequireEnvFrom
spec:
  crd:
    spec:
      names:
        kind: k8sRequireEnvFrom
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8srequireenvfrom

      violation[{"msg": msg}] {
        container := input.review.object.spec.containers[_]
        not container.envFrom
        msg := sprintf("Container '%s' must define envFrom", [container.name])
      }